home-assistant:
  deploymentStrategy:
    type: Recreate
  timezone: "America/Chicago"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - hass2.sievert.fun
    tls:
      - secretName: hass-tls
        hosts:
          - hass2.sievert.fun
  image:
    tag: 0.118.5
