home-assistant:
  deploymentStrategy:
    type: Recreate
  timezone: "America/Chicago"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - hass2.sievert.fun
    tls:
      - secretName: hass-tls
        hosts:
          - hass2.sievert.fun
  image:
    tag: 0.118.5
  vscode:
    enabled: true
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      path: /
      hosts:
        - vshass.sievert.fun
      tls: []
        - secretName: vshass-tls
          hosts:
            - vshass.sievert.fun
  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
