apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: unifi
  name: btmon
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.5.11
  ports:
  - name: btmon
    port: 5000
    protocol: TCP
    targetPort: btmon
  selector:
    app.kubernetes.io/name: unifi
  sessionAffinity: None
  type: LoadBalancer
