apiVersion: v1
kind: ConfigMap
metadata:
  name: btmon-cfg
data:
  btmon.cfg: |-
    [source]
    device_type = gem
    ip_read = true
    ip_port = 5000
    ip_mode = server
    reverse_polarity = 1
    include_current = true
    full_serials = true

    [influxdb]
    influxdb_out = true
    influxdb_host = influxdb.influxdb
    influxdb_port = 8086
    influxdb_upload_period = 10
    influxdb_database = btmon
    influxdb_measurement = energy
    influxdb_mode = row
    influxdb_db_schema = ecmreadext

    [oem]
    oem_out = false
    oem_url=http://emoncms.org/input/post
    oem_token = 90b2bd69a78bffaeb56d099c3719107c
