apiVersion: apps/v1
kind: Deployment
metadata:
  name: btmon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - args:
        - -c
        - /opt/btmon/btmon.py -c /config/btmon.cfg
        command:
        - /bin/sh
        image: rwojo/btmon-influx
        imagePullPolicy: Always
        name: btmon
        ports:
        - containerPort: 5000
          name: btmon
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: btmoncfg
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 256
          name: btmon-cfg
          optional: false
        name: btmoncfg
